export const ADD_TASK_LOADING = "ADD_TASK_LOADING";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const GET_TASK_LOADING = "GET_TASK_LOADING";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";